# ==========================================================================
#  Argon 主题 + 主题配置页（jerrykuku）
#  会在首次启动时由 files/etc/uci-defaults/99-custom-defaults 设为默认主题
# ==========================================================================
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_luci-app-argon-config=y
CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
