# ==========================================================================
#  顺手的常用组件（不需要可整段删除或把 ENABLE_EXTRAS=0）
# ==========================================================================
CONFIG_PACKAGE_luci-app-ttyd=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y

CONFIG_PACKAGE_luci-app-commands=y
CONFIG_PACKAGE_luci-i18n-commands-zh-cn=y

CONFIG_PACKAGE_luci-app-filemanager=y

# 多核（AN7581 四核）中断均衡
CONFIG_PACKAGE_irqbalance=y
CONFIG_PACKAGE_luci-app-irqbalance=y
